name: Deploy Rata Audaz Final
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Crear config.js
        run: |
          echo "const CONFIG = {" > config.js
          echo "  WEATHER_API_KEY: '${{ secrets.WEATHER_API_KEY }}'," >> config.js
          echo "  CITY: '${{ secrets.CITY }}'," >> config.js
          echo "  UNITS: 'metric'," >> config.js
          echo "  LANG: 'es'" >> config.js
          echo "};" >> config.js  

      - name: Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .        # Sube todo lo que hay en la carpeta raíz
          branch: gh-pages # A la rama gh-pages
          clean: false     # ¡IMPORTANTE! No borres lo que el robot creó antes
