name: Deploy Rata Audaz Final
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Creamos la plantilla exacta
      - name: Crear plantilla config.js
        run: |
          echo "const CONFIG = { WEATHER_API_KEY: 'REPLACE_ME_API', CITY: 'REPLACE_ME_CITY', UNITS: 'metric', LANG: 'es' };" > config.js

      # 2. Rellenamos buscando las etiquetas de texto
      - name: Rellenar config.js con los Secrets
        run: |
          sed -i "s/REPLACE_ME_API/${{ secrets.WEATHER_API_KEY }}/g" config.js
          sed -i "s/REPLACE_ME_CITY/${{ secrets.CITY }}/g" config.js

      # 3. Enviamos todo a la rama de internet (gh-pages)
      # 3. Enviamos todo a la web
      - name: Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .        # La raíz del proyecto
          branch: gh-pages
          target-folder: . # Forzamos que lo ponga en la raíz de la web
          clean: false
